FROM ubuntu

WORKDIR /CompileAPI/
COPY . .
CMD ["ls"]
#Install Lean4 on the container.
#RUN apt-get update
#RUN apt-get install -y curl
#RUN apt-get install -y wget
#RUN apt-get -y install sudo
#RUN apt-get -y install python3.9
#RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
#USER docker
#RUN exec bash
#CMD ["python3","/temp/main.py"]